[package]
name = "hlist_derive"
version = "0.1.0"
edition = "2018"
authors = ["Chris Campbell <campbell@plausible.coop>"]

[lib]
proc-macro = true

[dependencies]
syn = "1.0.5"
quote = "1.0.2"
proc-macro2 = "1.0.1"
